### ISSUE TITLE
PlanetShine tries/fails to parse DistantObject configs

### ISSUE THREAD

**Issue by MOARdV** [valerian/ksp-planetshine#14]
I assume this is some legacy code. PlanetShine tries parsing the CelestialBodyColor nodes used by DistantObjectEnhancement, and it logs a lot of errors (trapped exceptions from a try/catch block).  I realize these are handled exceptions, and they're not really errors, but I think it'd be better not to try to parse CelestialBodyColor nodes so the log doesn't clutter with

```
[ERR 09:32:28.927] [PlanetShine] An exception occured reading CelestialBodyColor node:
CelestialBodyColor
{
    name = Bop
    color = 100,86,76
}

The exception was:
System.ArgumentNullException: Argument cannot be null.
Parameter name: s
  at System.Double.Parse (System.String s, NumberStyles style, IFormatProvider provider) [0x00000] in <filename unknown>:0 
  at System.Single.Parse (System.String s) [0x00000] in <filename unknown>:0 
  at PlanetShine.ConfigManager.LoadBody (.ConfigNode bodySettings) [0x00000] in <filename unknown>:0 
```

(and so forth, once per world).

**Comment by valerian** [comment]
Ah yes thank you for reminding me of that, I had forgotten about it, I kept parsing CelestialBodyColor for backward compatibility of my first versions, but I can remove that behavior now.

**Comment by valerian** [comment]
Done in the dev version
